import type { IColumn } from '../types/table'

export const Columns: readonly IColumn[] = Object.freeze([
	{
		id: crypto.randomUUID(),
		field: 'dateOfReceipt',
		name: 'Дата поступления',
		type: 'date',
		width: 120,
		allowSort: true,
	},
	{
		id: crypto.randomUUID(),
		field: 'name',
		name: 'Наименование в 1С',
		type: 'text',
		width: 250,
		allowSort: true,
	},
	{
		id: crypto.randomUUID(),
		field: 'erpName',
		name: 'Наименование в ERP',
		type: 'text',
		width: 180,
		allowSort: true,
	},
	{
		id: crypto.randomUUID(),
		field: 'supplierBatch',
		name: 'Партия поставщика',
		type: 'text',
		width: 120,
		allowSort: true,
	},
	{
		id: crypto.randomUUID(),
		field: 'bigBagNumber',
		name: '№ б/б поставщика',
		type: 'text',
		width: 120,
		allowSort: true,
	},
	{
		id: crypto.randomUUID(),
		field: 'regNumber',
		name: 'Регистрационный №',
		type: 'text',
		width: 120,
		allowSort: true,
	},
	{
		id: crypto.randomUUID(),
		field: 'document',
		name: 'Документ приобретения',
		type: 'text',
		width: 200,
		allowSort: true,
	},
	{
		id: crypto.randomUUID(),
		field: 'supplier',
		name: 'Поставщик',
		type: 'text',
		width: 200,
		allowSort: true,
	},
	{
		id: crypto.randomUUID(),
		field: 'supplierName',
		name: 'Наименование поставщика',
		type: 'text',
		width: 200,
		allowSort: true,
	},
	{
		id: crypto.randomUUID(),
		field: 'markOnRelease',
		name: 'Отметка о выдаче в производство',
		type: 'text',
		width: 150,
		allowSort: true,
	},
	{
		id: crypto.randomUUID(),
		field: 'purpose',
		name: 'Назначение ИГ',
		type: 'text',
		width: 150,
		allowSort: true,
	},
	{
		id: crypto.randomUUID(),
		field: 'number1c',
		name: '№ ПО в 1С',
		type: 'text',
		width: 120,
		allowSort: true,
	},
	{
		id: crypto.randomUUID(),
		field: 'act',
		name: '№ Акта',
		type: 'text',
		width: 120,
		allowSort: true,
	},
	{
		id: crypto.randomUUID(),
		field: 'productionDate',
		name: 'Дата производства',
		type: 'date',
		width: 120,
		allowSort: true,
	},
	{
		id: crypto.randomUUID(),
		field: 'extendingMark',
		name: 'Отметка о продлении срока годности',
		type: 'text',
		width: 120,
		allowSort: true,
	},
	{
		id: crypto.randomUUID(),
		field: 'place',
		name: 'Место хранения',
		type: 'text',
		width: 120,
		allowSort: true,
	},
	{
		id: crypto.randomUUID(),
		field: 'notes',
		name: 'Примечание',
		type: 'text',
		width: 200,
		allowSort: true,
	},
])
